# Generated by Django 4.2.7 on 2023-11-28 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=30)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('rut', models.CharField(max_length=12)),
                ('direccion', models.CharField(max_length=100)),
                ('fono', models.FloatField()),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
    ]
