# Generated by Django 4.2.7 on 2023-11-30 15:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='fono',
            field=models.CharField(max_length=8, validators=[django.core.validators.MaxLengthValidator(limit_value=8, message='El teléfono debe ser de 8 caracteres')]),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='rut',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
