# Generated by Django 4.2.7 on 2023-12-01 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_userprofile_apellido_userprofile_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
