# Generated by Django 4.2.7 on 2023-12-04 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_formulario_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='contacto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
