# Generated by Django 4.2.7 on 2023-12-04 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_alter_formulario_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
