# Generated by Django 4.2.7 on 2023-12-04 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_alter_formulario_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='formulario_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
