# Generated by Django 4.2.7 on 2023-12-05 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_alter_formulario_formulario_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
