# Generated by Django 4.2.7 on 2023-12-05 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_alter_formulario_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
