# Generated by Django 4.2.7 on 2023-12-05 14:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_alter_formulario_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='direccio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telefono',
            field=models.CharField(blank=True, max_length=9, null=True, validators=[django.core.validators.MaxLengthValidator(limit_value=9, message='El teléfono debe ser de 9 caracteres')]),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='fono',
            field=models.CharField(max_length=9, validators=[django.core.validators.MaxLengthValidator(limit_value=9, message='El teléfono debe ser de 9 caracteres')]),
        ),
    ]
