# Generated by Django 4.2.7 on 2023-12-06 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_userprofile_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='rut',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
