# Generated by Django 4.2.7 on 2023-12-06 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_userprofile_rut'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='mail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
