# Generated by Django 4.2.7 on 2023-12-06 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0016_formulario_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
